/*
 * TI's FM Stack
 *
 * Copyright 2001-2008 Texas Instruments, Inc. - http://www.ti.com/
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and  
 * limitations under the License.
 */
/*******************************************************************************\
*
*   FILE NAME:      mcp_hal_log_common.c
*
*   BRIEF:          This file defines the API of the MCP HAL log MACROs.
*
*   DESCRIPTION:  
*
*   AUTHOR:         Chen Ganir
\*******************************************************************************/

#include "mcp_hal_log.h"
#include "mcp_hal_string.h"

/*
 * Keep in sync :
 * McpHalLogModuleName (in mcp_hal_log_common.c)
 * MCP_HAL_LogLevelMaskArray (in mcp_hal_log_common.c)
 * McpHalLogModuleId_e (in mcp_hal_log.h)
 */
McpHalLogModule_t MCP_HAL_LOG_Modules[] = {
    {MCP_HAL_LOG_DEFALT_DEBUG_LEVEL_MASK,       "UNKNOWN"}, /*    MCP_HAL_LOG_MODULE_TYPE_UNKNOWN */
    {MCP_HAL_LOG_DEFALT_DEBUG_LEVEL_MASK,       "BTL_BMG"}, /*    MCP_HAL_LOG_MODULE_TYPE_BMG   */ 
    {MCP_HAL_LOG_DEFALT_DEBUG_LEVEL_MASK,       "BTL_SPP"}, /*    MCP_HAL_LOG_MODULE_TYPE_SPP*/ 
    {MCP_HAL_LOG_DEFALT_DEBUG_LEVEL_MASK,       "BTL_OPPC"}, /*    MCP_HAL_LOG_MODULE_TYPE_OPPC */ 
    {MCP_HAL_LOG_DEFALT_DEBUG_LEVEL_MASK,       "BTL_OPPS"}, /*    MCP_HAL_LOG_MODULE_TYPE_OPPS */
    {MCP_HAL_LOG_DEFALT_DEBUG_LEVEL_MASK,       "BTL_BPPSND"}, /*    MCP_HAL_LOG_MODULE_TYPE_BPPSND */ 
    {MCP_HAL_LOG_DEFALT_DEBUG_LEVEL_MASK,       "BTL_PBAPS"}, /*    MCP_HAL_LOG_MODULE_TYPE_PBAPS   */ 
    {MCP_HAL_LOG_DEFALT_DEBUG_LEVEL_MASK,       "BTL_PAN"}, /*    MCP_HAL_LOG_MODULE_TYPE_PAN   */ 
    {MCP_HAL_LOG_DEFALT_DEBUG_LEVEL_MASK,       "BTL_AVRCTG"}, /*    MCP_HAL_LOG_MODULE_TYPE_AVRCPTG*/
    {MCP_HAL_LOG_DEFALT_DEBUG_LEVEL_MASK,       "BTL_FTPS"}, /*    MCP_HAL_LOG_MODULE_TYPE_FTPS */ 
    {MCP_HAL_LOG_DEFALT_DEBUG_LEVEL_MASK,       "BTL_FTPC"}, /*    MCP_HAL_LOG_MODULE_TYPE_FTPC */ 
    {MCP_HAL_LOG_DEFALT_DEBUG_LEVEL_MASK,       "BTL_VG"}, /*    MCP_HAL_LOG_MODULE_TYPE_VG */ 
    {MCP_HAL_LOG_DEFALT_DEBUG_LEVEL_MASK,       "BTL_AG"}, /*    MCP_HAL_LOG_MODULE_TYPE_AG */
    {MCP_HAL_LOG_DEFALT_DEBUG_LEVEL_MASK,       "BTL_RFCOMM"}, /*    MCP_HAL_LOG_MODULE_TYPE_RFCOMM*/ 
    {MCP_HAL_LOG_DEFALT_DEBUG_LEVEL_MASK,       "BTL_A2DP"}, /*    MCP_HAL_LOG_MODULE_TYPE_A2DP */ 
    {MCP_HAL_LOG_DEFALT_DEBUG_LEVEL_MASK,       "BTL_HID"}, /*    MCP_HAL_LOG_MODULE_TYPE_HID   */ 
    {MCP_HAL_LOG_DEFALT_DEBUG_LEVEL_MASK,       "BTL_MDG"}, /*    MCP_HAL_LOG_MODULE_TYPE_MDG   */
    {MCP_HAL_LOG_DEFALT_DEBUG_LEVEL_MASK,       "BTL_BIPINT"}, /*    MCP_HAL_LOG_MODULE_TYPE_BIPINT*/ 
    {MCP_HAL_LOG_DEFALT_DEBUG_LEVEL_MASK,       "BTL_BIPRSP"}, /*    MCP_HAL_LOG_MODULE_TYPE_BIPRSP*/ 
    {MCP_HAL_LOG_DEFALT_DEBUG_LEVEL_MASK,       "BTL_SAPS"}, /*    MCP_HAL_LOG_MODULE_TYPE_SAPS */ 
    {MCP_HAL_LOG_DEFALT_DEBUG_LEVEL_MASK,       "BTL_COMMON"}, /*    MCP_HAL_LOG_MODULE_TYPE_COMMON*/
    {MCP_HAL_LOG_DEFALT_DEBUG_LEVEL_MASK,       "BTL_L2CAP"}, /*    MCP_HAL_LOG_MODULE_TYPE_L2CAP   */ 
    {MCP_HAL_LOG_DEFALT_DEBUG_LEVEL_MASK,       "BTL_OPP"}, /*    MCP_HAL_LOG_MODULE_TYPE_OPP   */ 
    {MCP_HAL_LOG_DEFALT_DEBUG_LEVEL_MASK,       "BTL_FTP"}, /*    MCP_HAL_LOG_MODULE_TYPE_FTP   */ 
    {MCP_HAL_LOG_DEFALT_DEBUG_LEVEL_MASK,       "PM"}, /*    MCP_HAL_LOG_MODULE_TYPE_PM */
    {MCP_HAL_LOG_DEFALT_DEBUG_LEVEL_MASK,       "BTDRV"}, /*    MCP_HAL_LOG_MODULE_TYPE_BTDRV   */
    {MCP_HAL_LOG_DEFALT_DEBUG_LEVEL_MASK,       "UNICODE"}, /*    MCP_HAL_LOG_MODULE_TYPE_UNICODE          */  
    {MCP_HAL_LOG_DEFALT_DEBUG_LEVEL_MASK,       "BSC"}, /*    MCP_HAL_LOG_MODULE_TYPE_BSC           */ 
    {MCP_HAL_LOG_DEFALT_DEBUG_LEVEL_MASK,       "BTSTACK"}, /*    MCP_HAL_LOG_MODULE_TYPE_BTSTACK*/ 
    {MCP_HAL_LOG_DEFALT_DEBUG_LEVEL_MASK,       "FMCOMMON"}, /*    MCP_HAL_LOG_MODULE_TYPE_FMSTACK*/
    {MCP_HAL_LOG_DEFALT_DEBUG_LEVEL_MASK,       "FMPOOL"}, /*    MCP_HAL_LOG_MODULE_TYPE_FMSTACK*/
    {MCP_HAL_LOG_DEFALT_DEBUG_LEVEL_MASK,       "FMCORE"}, /*    MCP_HAL_LOG_MODULE_TYPE_FMSTACK*/
    {MCP_HAL_LOG_DEFALT_DEBUG_LEVEL_MASK,       "FMOS"}, /*    MCP_HAL_LOG_MODULE_TYPE_FMSTACK*/
    {MCP_HAL_LOG_DEFALT_DEBUG_LEVEL_MASK,       "FMUTILS"}, /*    MCP_HAL_LOG_MODULE_TYPE_FMSTACK*/
    {MCP_HAL_LOG_DEFALT_DEBUG_LEVEL_MASK,       "FMRX"}, /*    MCP_HAL_LOG_MODULE_TYPE_FMSTACK*/
    {MCP_HAL_LOG_DEFALT_DEBUG_LEVEL_MASK,       "FMRXSM"}, /*    MCP_HAL_LOG_MODULE_TYPE_FMSTACK*/
    {MCP_HAL_LOG_DEFALT_DEBUG_LEVEL_MASK,       "FMTX"}, /*    MCP_HAL_LOG_MODULE_TYPE_FMSTACK*/
    {MCP_HAL_LOG_DEFALT_DEBUG_LEVEL_MASK,       "FMTXSM"}, /*    MCP_HAL_LOG_MODULE_TYPE_FMSTACK*/
    {MCP_HAL_LOG_DEFALT_DEBUG_LEVEL_MASK,       "CCM"}, /*    MCP_HAL_LOG_MODULE_TYPE_FMSTACK*/
    {MCP_HAL_LOG_DEFALT_DEBUG_LEVEL_MASK,       "CCM_IM"}, /*    MCP_HAL_LOG_MODULE_TYPE_FMSTACK*/
    {MCP_HAL_LOG_DEFALT_DEBUG_LEVEL_MASK,       "CCM_VAC"}, /*    MCP_HAL_LOG_MODULE_TYPE_FMSTACK*/
    {MCP_HAL_LOG_DEFALT_DEBUG_LEVEL_MASK,       "CCM_CAL"}, /*    MCP_HAL_LOG_MODULE_TYPE_FMSTACK*/
    {MCP_HAL_LOG_DEFALT_DEBUG_LEVEL_MASK,       "FRAME"}, /*    MCP_HAL_LOG_MODULE_TYPE_FMSTACK*/
    {MCP_HAL_LOG_DEFALT_DEBUG_LEVEL_MASK,       "FS"}, /*    MCP_HAL_LOG_MODULE_TYPE_FS            */ 
    {MCP_HAL_LOG_DEFALT_DEBUG_LEVEL_MASK,       "MODEM"}, /*    MCP_HAL_LOG_MODULE_TYPE_MODEM              */ 
    {MCP_HAL_LOG_DEFALT_DEBUG_LEVEL_MASK,       "OS"}, /*    MCP_HAL_LOG_MODULE_TYPE_OS            */ 
    {MCP_HAL_LOG_DEFALT_DEBUG_LEVEL_MASK,       "SCRIPT_PROCESSOR"}, /*    MCP_HAL_LOG_MODULE_TYPE_SCRIPT_PROCESSOR */
    {MCP_HAL_LOG_DEFALT_DEBUG_LEVEL_MASK,       "ASSERT"}, /*    MCP_HAL_LOG_MODULE_TYPE_ASSERT */
    {MCP_HAL_LOG_DEFALT_DEBUG_LEVEL_MASK,       "MCP_HAL_FS"}, /*    MCP_HAL_LOG_MODULE_TYPE_HAL_FS */
    {MCP_HAL_LOG_DEFALT_DEBUG_LEVEL_MASK,       "BTHAL_MM"}, /* MCP_HAL_LOG_MODULE_TYPE_BTHAL_MM */
    
    
    {MCP_HAL_LOG_DEFALT_DEBUG_LEVEL_MASK,       "BTBUS_EVENTS"}, /* MCP_HAL_LOG_MODULE_TYPE_BTBUS_MAIN_EVENTS */
    {MCP_HAL_LOG_DEFALT_DEBUG_LEVEL_MASK,       "BTBUS_MAIN"}, /* MCP_HAL_LOG_MODULE_TYPE_BTBUS_MAIN */
    {MCP_HAL_LOG_DEFALT_DEBUG_LEVEL_MASK,       "BTBUS_TIMEOUTS"}, /* MCP_HAL_LOG_MODULE_TYPE_BTBUS_TIMEOUTS */
    {MCP_HAL_LOG_DEFALT_DEBUG_LEVEL_MASK,       "BTBUS_UTIL"}, /* MCP_HAL_LOG_MODULE_TYPE_BTBUS_UTIL */
    {MCP_HAL_LOG_DEFALT_DEBUG_LEVEL_MASK,       "CLIENT_MAIN"}, /* MCP_HAL_LOG_MODULE_TYPE_BTBUS_CLIENT_MAIN */
    {MCP_HAL_LOG_DEFALT_DEBUG_LEVEL_MASK,       "CLIENT_A2DP"}, /* MCP_HAL_LOG_MODULE_TYPE_BTBUS_CLIENT_A2DP */
    {MCP_HAL_LOG_DEFALT_DEBUG_LEVEL_MASK,       "CLIENT_AG"}, /* MCP_HAL_LOG_MODULE_TYPE_BTBUS_CLIENT_AG */
    {MCP_HAL_LOG_DEFALT_DEBUG_LEVEL_MASK,       "CLIENT_AVRCP"}, /* MCP_HAL_LOG_MODULE_TYPE_BTBUS_CLIENT_AVRCP */
    {MCP_HAL_LOG_DEFALT_DEBUG_LEVEL_MASK,       "CLIENT_BMG"}, /* MCP_HAL_LOG_MODULE_TYPE_BTBUS_CLIENT_BMG */
    {MCP_HAL_LOG_DEFALT_DEBUG_LEVEL_MASK,       "CLIENT_COMMON"}, /* MCP_HAL_LOG_MODULE_TYPE_BTBUS_CLIENT_COMMON */
    {MCP_HAL_LOG_DEFALT_DEBUG_LEVEL_MASK,       "CLIENT_FMRX"}, /* MCP_HAL_LOG_MODULE_TYPE_BTBUS_CLIENT_FMRX */
    {MCP_HAL_LOG_DEFALT_DEBUG_LEVEL_MASK,       "CLIENT_FMTX"}, /* MCP_HAL_LOG_MODULE_TYPE_BTBUS_CLIENT_FMTX */
    {MCP_HAL_LOG_DEFALT_DEBUG_LEVEL_MASK,       "CLIENT_FTPC"}, /* MCP_HAL_LOG_MODULE_TYPE_BTBUS_CLIENT_FTPC */
    {MCP_HAL_LOG_DEFALT_DEBUG_LEVEL_MASK,       "CLIENT_FTPS"}, /* MCP_HAL_LOG_MODULE_TYPE_BTBUS_CLIENT_FTPS */
    {MCP_HAL_LOG_DEFALT_DEBUG_LEVEL_MASK,       "CLIENT_HALMM"}, /* MCP_HAL_LOG_MODULE_TYPE_BTBUS_CLIENT_HALMM */
    {MCP_HAL_LOG_DEFALT_DEBUG_LEVEL_MASK,       "CLIENT_HALPB"}, /* MCP_HAL_LOG_MODULE_TYPE_BTBUS_CLIENT_HALPB */
    {MCP_HAL_LOG_DEFALT_DEBUG_LEVEL_MASK,       "CLIENT_HIDH"}, /* MCP_HAL_LOG_MODULE_TYPE_BTBUS_CLIENT_HIDH */
    {MCP_HAL_LOG_DEFALT_DEBUG_LEVEL_MASK,       "CLIENT_MDG"}, /* MCP_HAL_LOG_MODULE_TYPE_BTBUS_CLIENT_MDG */
    {MCP_HAL_LOG_DEFALT_DEBUG_LEVEL_MASK,       "CLIENT_OPPC"}, /* MCP_HAL_LOG_MODULE_TYPE_BTBUS_CLIENT_OPPC */
    {MCP_HAL_LOG_DEFALT_DEBUG_LEVEL_MASK,       "CLIENT_OPPS"}, /* MCP_HAL_LOG_MODULE_TYPE_BTBUS_CLIENT_OPPS */
    {MCP_HAL_LOG_DEFALT_DEBUG_LEVEL_MASK,       "CLIENT_PBAPS"}, /* MCP_HAL_LOG_MODULE_TYPE_BTBUS_CLIENT_PBAPS */
    {MCP_HAL_LOG_DEFALT_DEBUG_LEVEL_MASK,       "CLIENT_XXX"}, /* MCP_HAL_LOG_MODULE_TYPE_BTBUS_CLIENT_XXX */
    {MCP_HAL_LOG_DEFALT_DEBUG_LEVEL_MASK,       "CLIENT_SPP"}, /* MCP_HAL_LOG_MODULE_TYPE_BTBUS_CLIENT_SPP */
    {MCP_HAL_LOG_DEFALT_DEBUG_LEVEL_MASK,       "SERVER_MAIN"}, /* MCP_HAL_LOG_MODULE_TYPE_BTBUS_SERVER_MAIN */
    {MCP_HAL_LOG_DEFALT_DEBUG_LEVEL_MASK,       "SERVER_A2DP"}, /* MCP_HAL_LOG_MODULE_TYPE_BTBUS_SERVER_A2DP */
    {MCP_HAL_LOG_DEFALT_DEBUG_LEVEL_MASK,       "SERVER_AG"}, /* MCP_HAL_LOG_MODULE_TYPE_BTBUS_SERVER_AG */
    {MCP_HAL_LOG_DEFALT_DEBUG_LEVEL_MASK,       "SERVER_AVRCP"}, /* MCP_HAL_LOG_MODULE_TYPE_BTBUS_SERVER_AVRCP */
    {MCP_HAL_LOG_DEFALT_DEBUG_LEVEL_MASK,       "SERVER_BMG"}, /* MCP_HAL_LOG_MODULE_TYPE_BTBUS_SERVER_BMG */
    {MCP_HAL_LOG_DEFALT_DEBUG_LEVEL_MASK,       "SERVER_COMMON"}, /* MCP_HAL_LOG_MODULE_TYPE_BTBUS_SERVER_COMMON */
    {MCP_HAL_LOG_DEFALT_DEBUG_LEVEL_MASK,       "SERVER_FMRX"}, /* MCP_HAL_LOG_MODULE_TYPE_BTBUS_SERVER_FMRX */
    {MCP_HAL_LOG_DEFALT_DEBUG_LEVEL_MASK,       "SERVER_FMTX"}, /* MCP_HAL_LOG_MODULE_TYPE_BTBUS_SERVER_FMTX */
    {MCP_HAL_LOG_DEFALT_DEBUG_LEVEL_MASK,       "SERVER_FTPC"}, /* MCP_HAL_LOG_MODULE_TYPE_BTBUS_SERVER_FTPC */
    {MCP_HAL_LOG_DEFALT_DEBUG_LEVEL_MASK,       "SERVER_FTPS"}, /* MCP_HAL_LOG_MODULE_TYPE_BTBUS_SERVER_FTPS */
    {MCP_HAL_LOG_DEFALT_DEBUG_LEVEL_MASK,       "SERVER_HALMM"}, /* MCP_HAL_LOG_MODULE_TYPE_BTBUS_SERVER_HALMM */
    {MCP_HAL_LOG_DEFALT_DEBUG_LEVEL_MASK,       "SERVER_HALPB"}, /* MCP_HAL_LOG_MODULE_TYPE_BTBUS_SERVER_HALPB */
    {MCP_HAL_LOG_DEFALT_DEBUG_LEVEL_MASK,       "SERVER_HIDH"}, /* MCP_HAL_LOG_MODULE_TYPE_BTBUS_SERVER_HIDH */
    {MCP_HAL_LOG_DEFALT_DEBUG_LEVEL_MASK,       "SERVER_MDG"}, /* MCP_HAL_LOG_MODULE_TYPE_BTBUS_SERVER_MDG */
    {MCP_HAL_LOG_DEFALT_DEBUG_LEVEL_MASK,       "SERVER_OPPC"}, /* MCP_HAL_LOG_MODULE_TYPE_BTBUS_SERVER_OPPC */
    {MCP_HAL_LOG_DEFALT_DEBUG_LEVEL_MASK,       "SERVER_OPPS"}, /* MCP_HAL_LOG_MODULE_TYPE_BTBUS_SERVER_OPPS */
    {MCP_HAL_LOG_DEFALT_DEBUG_LEVEL_MASK,       "SERVER_PBAPS"}, /* MCP_HAL_LOG_MODULE_TYPE_BTBUS_SERVER_PBAPS */
    {MCP_HAL_LOG_DEFALT_DEBUG_LEVEL_MASK,       "SERVER_XXX"}, /* MCP_HAL_LOG_MODULE_TYPE_BTBUS_SERVER_XXX */
    {MCP_HAL_LOG_DEFALT_DEBUG_LEVEL_MASK,       "SERVER_SPP"}, /* MCP_HAL_LOG_MODULE_TYPE_BTBUS_SERVER_SPP */
    {MCP_HAL_LOG_DEFALT_DEBUG_LEVEL_MASK,       "SERVER_UTILS"}, /* MCP_HAL_LOG_MODULE_TYPE_BTBUS_UTILS */
    {MCP_HAL_LOG_DEFALT_DEBUG_LEVEL_MASK,       "USER_1"}, /* MCP_HAL_LOG_MODULE_TYPE_USER_DEFINED_001 */
    {MCP_HAL_LOG_DEFALT_DEBUG_LEVEL_MASK,       "USER_2"}, /* MCP_HAL_LOG_MODULE_TYPE_USER_DEFINED_002 */
    {MCP_HAL_LOG_DEFALT_DEBUG_LEVEL_MASK,       "USER_3"}, /* MCP_HAL_LOG_MODULE_TYPE_USER_DEFINED_003 */
    {MCP_HAL_LOG_DEFALT_DEBUG_LEVEL_MASK,       "USER_4"}, /* MCP_HAL_LOG_MODULE_TYPE_USER_DEFINED_004 */
    {MCP_HAL_LOG_DEFALT_DEBUG_LEVEL_MASK,       "USER_5"}, /* MCP_HAL_LOG_MODULE_TYPE_USER_DEFINED_005 */
    {MCP_HAL_LOG_DEFALT_DEBUG_LEVEL_MASK,       "USER_6"}, /* MCP_HAL_LOG_MODULE_TYPE_USER_DEFINED_006 */
    {MCP_HAL_LOG_DEFALT_DEBUG_LEVEL_MASK,       "USER_7"}, /* MCP_HAL_LOG_MODULE_TYPE_USER_DEFINED_007 */
    {MCP_HAL_LOG_DEFALT_DEBUG_LEVEL_MASK,       "USER_8"}, /* MCP_HAL_LOG_MODULE_TYPE_USER_DEFINED_008 */
    {MCP_HAL_LOG_DEFALT_DEBUG_LEVEL_MASK,       "USER_9"}, /* MCP_HAL_LOG_MODULE_TYPE_USER_DEFINED_009 */
    {MCP_HAL_LOG_DEFALT_DEBUG_LEVEL_MASK,       "USER_10"},/* MCP_HAL_LOG_MODULE_TYPE_USER_DEFINED_010 */
    {MCP_HAL_LOG_INVALID_DEBUG_MASK,""}
};

const char* MCP_HAL_LOG_SetModuleName(McpHalLogModuleId_e moduleId,const char* name)
{
    if (moduleId > MCP_HAL_LOG_MODULE_TYPE_UNKNOWN && moduleId <= MCP_HAL_LOG_MODULE_TYPE_LAST && NULL != name)
    {
        MCP_HAL_STRING_StrnCpy(MCP_HAL_LOG_Modules[moduleId].name, name, MAX_MODULE_NAME_LENGTH-1);
        return MCP_HAL_LOG_Modules[moduleId].name;
    }
    return NULL;
}


const char* MCP_HAL_LOG_GetModuleName(McpHalLogModuleId_e moduleId)
{
    if (moduleId > MCP_HAL_LOG_MODULE_TYPE_UNKNOWN && moduleId <= MCP_HAL_LOG_MODULE_TYPE_LAST)
        return MCP_HAL_LOG_Modules[moduleId].name;
    else
        return "UNKNOWN";
}



